# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
!pip install mdutils

In [29]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [30]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)
np.show_config()

2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/anaconda3/Library/include
    lib directory: C:/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/anaconda3/Library/include
    lib directory: C:/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
Machine Information:
  b

#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
n=np.zeros(10,dtype="i")
print(n)

[0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)

In [14]:
print(n.size)

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [16]:
import numpy; numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
z=np.zeros(10,dtype=int)
z[4]=1
print(z)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [14]:
print(np.flip(z))
print(z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [24]:
n=np.arange(0,9).reshape(3,3)
print(n)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [25]:
x=np.array([1,2,0,0,4,0])
print(np.nonzero(x))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [29]:
n=np.ones((3,3),dtype="i")
print(n)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
n=np.random.randint(0,50,size=(3,3,3))
print(n)

[[[18 24 13]
  [17  9  6]
  [36 26 17]]

 [[45 39 40]
  [29  4 16]
  [24 41 38]]

 [[30 29  8]
  [11 45 18]
  [36 35  7]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
n=np.random.randint(0,121,size=(10,10))
print(n)
print(n.min())
print(n.max())

[[ 96  33  90  57  76 117  35  36   0  94]
 [104  58  85   7  27  90  20  63  69  37]
 [ 41  92  28  82  64  43  62  83   2 115]
 [  8  26  10  89   7  97  66  77  39   4]
 [ 66  40  41 101 107 117  15 106  62  64]
 [ 86  73  22 102 104  50 104  84  53  12]
 [  9  81 119  84  37  27  75   1   6 109]
 [  4  25  54  99  42  20  91  38 112  64]
 [ 71 117 120  54  46  78  25  53 108 113]
 [ 22  67  70  48 104  29 115  17   4 105]]
0
120


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
n=np.random.randint(0,31,size=(30))
print(n)
print(np.mean(n))


[25 15 28 23 27  8 20  0 12  8 16  1 13 11 21 23 17  2 16 30  0  8 14  5
 15 28 24  4 15  8]
14.566666666666666


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [49]:
n=np.ones((5,5),dtype="i")
n[1:-1,1:-1]=0
print(n)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
n=np.ones((5,5),dtype="i")
n[1:-1,1:-1]=0
print(n)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [52]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [55]:
v=[1,2,3,4]
n=np.diag(v,k=-1)
print(n)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [71]:
#n=np.array([[1,0,1,0],[0,1,0,1]])
#print(np.tile(n,(4,2)))

z = np.zeros((8,8), dtype=int)
z[::2,::2] = 1
z[1::2,1::2] = 1
print(z)


#LEARN INDICES() FUNCTION AND SUM() FUNCTION WITH AXIS
checkerboard = np.indices((8, 8)).sum(axis=0) % 2
print(checkerboard)

checkerboard = (np.indices((8, 8)).sum(axis=0)+1) % 2
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [78]:

#LEARN UNRAVAL_INDEX()

np.unravel_index(99, (6, 7, 8))
print(index)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [81]:
n=np.array([[1,0],[0,1]])
np.tile(n,(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [26]:


#THIS SOLUTION IS FOR NORMALIZING VALUE BETWEEN 0 AND 1 CALLED Min-max normalization
# THERE ARE OTHER TYPES OF NORMALIZATION TOO ONE GIVEN IN ANSWER(22) IS Standardization 
#  WHICH NORMALIZE DATA AROUND 0



# Step 1: Create a random 5x5 matrix (values 0 to 1)
matrix = np.random.rand(5, 5)
print("Original matrix:\n", matrix)

# Step 2: Find min and max
min_val = matrix.min()
max_val = matrix.max()

# Step 3: Apply min-max normalization
normalized_matrix = (matrix - min_val) / (max_val - min_val)
print("\nNormalized matrix:\n", normalized_matrix)

Original matrix:
 [[0.23896234 0.95725787 0.3083538  0.02801908 0.54454043]
 [0.65080491 0.74938909 0.48327634 0.28032069 0.80206152]
 [0.1686751  0.37462173 0.81723833 0.7592968  0.66972079]
 [0.2958262  0.23604856 0.73794529 0.11752696 0.07944227]
 [0.69778462 0.81500135 0.10851549 0.51683228 0.14582993]]

Normalized matrix:
 [[0.22700651 1.         0.30168211 0.         0.55585427]
 [0.67021075 0.77630208 0.48992494 0.27151429 0.8329855 ]
 [0.15136693 0.37299632 0.84931802 0.78696426 0.69056707]
 [0.28820053 0.22387086 0.76398685 0.09632387 0.05533905]
 [0.72076795 0.8469107  0.08662619 0.52603616 0.12678211]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [86]:


#LEARN HOW TO CREATE CUSTOM DATATYPE IN NUMPY


color_dtype = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('A', np.uint8)
])

print(color_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [88]:



#LEARN MATRIX MULTIPLICATION BOTH ELEMENT WISE AND MATRIX MULTIPLY



# Step 1: Create random matrices
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)

# Step 2: Matrix multiplication
C = np.dot(A, B)       # Option 1
# Or using @ operator
# C = A @ B

print("A shape:", A.shape)
print("B shape:", B.shape)
print("Result C shape:", C.shape)
print("\nResult C:\n", C)

A shape: (5, 3)
B shape: (3, 2)
Result C shape: (5, 2)

Result C:
 [[0.74069634 0.55316984]
 [0.44154651 0.27051463]
 [0.53463383 0.28201726]
 [1.0062466  0.71955001]
 [0.28274956 0.19432193]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [41]:


#LEARM ABOUT INPLACE AND NOT INPLACE OPERATION IN NUMPY

n=np.arange(11)
#n[ (n>3)&(n<8) ] *=-1
#print(n)
x=np.where((n>3)&(n<8) , -n , n)
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [44]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [54]:
Z = np.array([1, 2, 3])
Z**Z


array([ 1,  4, 27])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [58]:


#LEARN // (floor division)





#### 29. How to round away from zero a float array ? (★☆☆)

In [64]:


#LEARN ROUNDING FUNCTIONS IN NUMPY AND HOW TO ROUND AWAY FROM ZERO.


import numpy as np

Z = np.array([1.2, -1.2, 2.0, -2.0, 3.7, -3.7])

#print(np.ceil(Z))

rounded = np.sign(Z) * np.ceil(np.abs(Z))
print(rounded)


[ 2. -1.  2. -2.  4. -3.]
[ 2. -2.  2. -2.  4. -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [67]:



#LEARN HOW TO FIND INTERSECTION IN NUMPY (LEARN np.intersect1d & np.isin)

a=np.array([1,6,4,8,4,4,5,33,33,33])
b=np.array([0,5,12,8,6,4,13,33,33,33])

print(np.intersect1d(a,b))

[ 4  5  6  8 33]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [70]:


#np.sqrt() → real-valued math → returns nan for negatives
#np.emath.sqrt() → complex-aware → returns complex results
#nan never equals anything (even itself)   nan == anything  → False


print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\sagar suman\AppData\Local\Temp\ipykernel_9704\4142547497.py:6: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [75]:




#LEARN np.datetime64 and np.timedelta64



#DATE
today = np.datetime64('today', 'D')      
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


#DATE+TIME
now = np.datetime64('now')                
yesterday = now - np.timedelta64(1, 'D')
tomorrow = now + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Now:", now)
print("Tomorrow:", tomorrow)

Yesterday: 2026-01-10
Today: 2026-01-11
Tomorrow: 2026-01-12
Yesterday: 2026-01-09T21:57:25
Now: 2026-01-10T21:57:25
Tomorrow: 2026-01-11T21:57:25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [76]:


start = np.datetime64('2016-07-01')
end   = np.datetime64('2016-08-01')  # exclusive
#Note: np.arange excludes the end date, so we set it to first day of August.

dates = np.arange(start, end, dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [81]:
A = np.array([1., 2., 3.])
B = np.array([4., 5., 6.])

np.add(A,B,out=B)
np.divide(A,-2,out=A)
np.multiply(A,B,out=B)

print(B)

[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [83]:

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


[5. 5. 9. 4. 1. 0. 8. 6. 7. 2.]
[5. 5. 9. 4. 1. 0. 8. 6. 7. 2.]
[5. 5. 9. 4. 1. 0. 8. 6. 7. 2.]
[5 5 9 4 1 0 8 6 7 2]
[5. 5. 9. 4. 1. 0. 8. 6. 7. 2.]


37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 

In [89]:


Z = np.tile(np.arange(5), (5, 1))
print(Z)

Z = np.zeros((5, 5), dtype=int) + np.arange(5)
print(Z)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [93]:

#LEARN GENERATOR FUNCTION

def gen():
    for i in range(10):
        yield i


Z=np.fromiter(gen(),dtype=int,count=-1)  #COUNT =-1 MEANS GET ALL THE VALUE FROM GENERATOR gen(),USING THIS WE CAN EXPLICITLY TELL NO OF VALUE TO ACCEPT
print(Z)
answer(38)

[0 1 2 3 4 5 6 7 8 9]
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [96]:


Z=np.linspace(0,1,12)[1:-1]    #LINESPACE CREATES EVENLY SPACED ARRAY BETWEEN TWO RANGE
print(Z)


#ALTERNATIVE                           linespace includes stop value and arange exclude stop value.

Z = (np.arange(1, 11)) / 11
print(Z)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [111]:


Z=np.random.randint(1,10,(10))
Z.sort()              #Z.sort() — sorts in-place
print(Z)
print(np.sort(Z))     #np.sort(Z) — returns a new sorted array



[2 3 4 5 6 6 7 7 7 9]
[2 3 4 5 6 6 7 7 7 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [114]:


#For very small arrays, Python’s built-in sum() can be faster than np.sum()
#for small arrays, the overhead of calling NumPy machinery dominates the cost.


Z = np.arange(10)
print(sum(Z))

45


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [118]:


# =========================================================
# Element-wise comparison
# =========================================================
# A == B performs element-wise comparison and returns
# a boolean array, NOT a single True/False value.

A = np.array([1, 2, 3])
B = np.array([1, 2, 4])

print("A == B :", A == B)     # [ True  True False ]


# =========================================================
# np.all()
# =========================================================
# np.all() returns True ONLY if all elements are True

print("np.all(A == B):", np.all(A == B))


# =========================================================
# Another use of np.all()
# Check if all elements satisfy a condition

A = np.array([2, 4, 6])
print("All elements even:", np.all(A % 2 == 0))


# =========================================================
# Floating-point comparison issue
# =========================================================
# Floating-point numbers are not exact due to binary storage.
# Example: 0.1 + 0.2 is NOT exactly equal to 0.3

a = 0.1 + 0.2
b = 0.3

print("a == b :", a == b)
print("np.allclose(a, b):", np.allclose(a, b))


# =========================================================
# np.array_equal()
# =========================================================
# np.array_equal() checks:
# - Same shape
# - Same values
# - Same dtype

A = np.array([1, 2, 3])
B = np.array([1, 2, 3])

print("np.array_equal(A, B):", np.array_equal(A, B))


A == B : [ True  True False]
np.all(A == B): False
All elements even: True
a == b : False
np.allclose(a, b): True
np.array_equal(A, B): True


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)